import { Container } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { Home } from "../src/components/Home";
import styles from "../styles/Home.module.css";

export default () => {
  return (
    <>
      <Head>
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};
