import {
  Box,
  Container,
  Heading,
  HStack,
  Icon,
  Img,
  Stack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef } from "react";
import { CheckCircle } from "react-feather";
import { Home } from "../src/components/Home";

export default function Thankyou() {
  const router = useRouter();
  const timeout = useRef(0);
  useEffect(() => {
    timeout.current = setTimeout(() => router.push("/"), 1000);
    return () => clearTimeout(timeout.current);
  }, []);

  return (
    <>
      <Head>
        <title>Thank you!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.lg" textAlign="center">
        <Stack h="100vh" align="center" justify="center">
          <Img src="/logo.svg" h={"50px"} />
          <HStack>
            <Heading>Submitted</Heading>
            <Icon as={CheckCircle} boxSize="2em" stroke="green.500" />
          </HStack>
          <Text>
            Thank you for your submission, we will get back to you as soon as
            possible.
          </Text>
        </Stack>
      </Container>
    </>
  );
}
