import {
  Button,
  Container,
  Heading,
  Icon,
  Img,
  Stack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { ArrowLeft } from "react-feather";
import Lottie from "react-lottie";
import checkLottieData from "../public/lottie/check.json";
import Link from "next/link";

export default function Thankyou() {
  const router = useRouter();
  // useTimeoutFn(() => router.push("/"), 2000);

  return (
    <>
      <Head>
        <title>Thank you!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.lg" textAlign="center">
        <Stack h="100vh" align="center" justify="center">
          <Img src="/logo.svg" h={"50px"} />
          <Lottie
            options={{
              loop: true,
              autoplay: true,
              animationData: checkLottieData,
            }}
            height={300}
            width={300}
          />
          <Heading>Submitted</Heading>
          <Text>
            Thank you for your submission, we will get back to you as soon as
            possible.
          </Text>
          <Link href="/">
            <Button leftIcon={<Icon as={ArrowLeft} />}>Back to home</Button>
          </Link>
        </Stack>
      </Container>
    </>
  );
}
